site_name: School Materials
docs_dir: docs
site_dir: site
site_url: https://kouril.dev

theme:
  name: material
  language: cs
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: starvex
      repo: school_materials

extra_css:
  - css/obsidian-like.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/contrib/auto-render.min.js
  - js/math-render.js

nav:
  - Úvod: index.md
  - MFF Státnice:
      - Společná část: mff_statnice/spec-main.md
      - Specializace: mff_statnice/spec-main.md
  - Výpisky:
      - Pokročilá diskrétní matematika:
          - Barvení grafů: mff_statnice/adv_discrete_math/Barvení grafů.md
          - Grafové minory: mff_statnice/adv_discrete_math/Grafové minory.md
          - Množiny a zobrazení: mff_statnice/adv_discrete_math/Množiny a zobrazení.md
          - Subvalence a ekvivalence množin: mff_statnice/adv_discrete_math/Subvalence a ekvivalence množin.md
          - Dobré uspořádání: mff_statnice/adv_discrete_math/Dobré uspořádání.md
          - Kreslení grafů na plochách: mff_statnice/adv_discrete_math/Kreslení grafů na plochách.md
          - Párování v grafech: mff_statnice/adv_discrete_math/Párování v grafech.md

      - Kombinatorika:
          - Catalanova čísla: mff_statnice/combinatorics/Catalanova čísla.md
          - Ramseyova čísla: mff_statnice/combinatorics/Ramseyova čísla.md
          - Vytvořující funkce: mff_statnice/combinatorics/Vytvořující funkce.md
          - Extremální kombinatorika: mff_statnice/combinatorics/Extremální kombinatorika.md
          - Ramseyovy věty: mff_statnice/combinatorics/Ramseyovy věty.md
          - Zobecněná binomická věta: mff_statnice/combinatorics/Zobecněná binomická věta.md
          - Odhady faktoriálu a kombinačních čísel: mff_statnice/combinatorics/Odhady faktoriálu a kombinačních čísel.md
          - Samoopravné kódy: mff_statnice/combinatorics/Samoopravné kódy.md

      - Diskrétní matematika:
          - Částečná uspořádání: mff_statnice/discrete_math/Částečná uspořádání.md
          - Hallova věta: mff_statnice/discrete_math/Hallova věta.md
          - Množiny a zobrazení: mff_statnice/discrete_math/Množiny a zobrazení.md
          - Princip inkluze a exkluze: mff_statnice/discrete_math/Princip inkluze a exkluze.md
          - Funkce: mff_statnice/discrete_math/Funkce.md
          - Kombinační čísla: mff_statnice/discrete_math/Kombinační čísla.md
          - Permutace: mff_statnice/discrete_math/Permutace.md
  - Teorie her:
      - Výpisky (PDF): alg_game_theory/build/main.pdf
