site_name: School Materials
site_url: https://kouril.dev
docs_dir: docs
site_dir: site

theme:
  name: material
  language: cs
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.annotate
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo

plugins:
  - search
  - obsidian:
      use_directory_urls: true

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: starvex
      repo: school_materials

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/contrib/auto-render.min.js
  - js/math-render.js

extra_css:
  - css/obsidian-like.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css

nav:
  - Úvod: index.md
  - MFF Státnice:
      - Společná část: mff_statnice/spec-main.md
      - Specializace: mff_statnice/spec-main.md
  - Teorie her:
      - Výpisky (PDF): alg_game_theory/build/main.pdf
